# Generated by Django 5.1.1 on 2025-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
