# Generated by Django 5.1.1 on 2024-12-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('max_pax', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('hire_price_per_hour', models.IntegerField()),
                ('aircraft_image_url', models.URLField()),
            ],
        ),
    ]
