# Generated by Django 5.1.1 on 2024-12-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avibot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='name',
            new_name='aircraft_name',
        ),
    ]
